### ISSUE TITLE
Is it possible to customize the dump-moves output ?

### ISSUE THREAD

**Issue by sb53systems** [dalegaard/klipper_estimator_test#1]
Hi Lasse,  
  
I am using Klipper_Estimator tool in one of my projects ([G-Code Flow and Temperature Controller](https://github.com/sb53systems/G-Code-Flow-Temperature-Controller)).  
I think this is the most powerful tool that calculates printing time accurately., I would have liked your help to adapt and optimize it for my use case.
  
- I need to reduce and customize the output of dump-moves mode; I need only the total time and the average flow for each move, if also possible to display the original G-Code line.  
  
- With ARC move, is it possible to show the total move time and average flow, the current version of Klipper Estimator cuts them into small segments (based on the parameter "mm_per_arc_segment": 0.1).  
  
- Users of my script were able to prove that the time estimated by Klipper-Estimator is very close even for Marlin and RRF firmware, the mechanism seems very close!  
In the config.json file, they put values ​​close to their firmware manually and it works! Is it possible to improve the time estimation for these firmware by supporting the acceleration change inside the G-Code with "M204 S"  
![image](https://github.com/user-attachments/assets/8f48e249-6817-4eb5-8e0c-9dfc23ae1a9b)  
  
This is my first experience with Github and I ask you to guide me on how this project can and should be done.  
  
I would appreciate your help or collaboration, thank you for your time.  
  
Best reguards,  
Salim  
Email : [sb53systems@gmail.com](mailto:sb53systems@gmail.com)  
Discord : sb53systems

**Comment by sb53systems** [comment]
I was able to remove the unwanted lines and reduce the output of dump-move mode to the example below  
![image](https://github.com/user-attachments/assets/5f051e70-147e-468a-b7a6-8f7c219a9b1f)  
  
see the changes made to the estimate.rc file  
https://github.com/Annex-Engineering/klipper_estimator/compare/master...sb53systems:klipper_estimator:master  
  
I still have to :  
- Add the original line of G-Code before the Flow and Time concerned.
- Displays the values ​​of an Arc move (G2/G3) in a single output.  
  
I would have liked to have your advice and help.  
  
Best reguards,  
Salim

**Comment by dalegaard** [comment]
Hi Salim,

I no longer use `klipper_estimator` and currently don't have time to help. Sorry :-(

Best regards,
Lasse
